-- Seed translated people and Family Echo family links. Re-running preserves admin edits.
insert into public.family_people(id,name_he,name_ru,deceased) values ('I1','עילאי ספובל','Илай Споваль',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I2','מיכאל ספובל','Михаил Споваль',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I3','ילנה פחמנוב','Елена Пахманов',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I4','אשר (איזיה) ספובל','Ашер (Изя) Споваль',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I5','זינה רובין','Зина Рубин',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I6','משה רובין','Моисей Рубин',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I7','בטיה רובין','Бетя Рубин',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I8','דינה וינוגרדסקי','Дина Виноградская',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I9','יעקב מירושניק','Яков Мирошник',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I10','קטיה ספובל','Катя Споваль',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I11','סימה רובין','Сима Рубин',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I12','דוד רובין','Давид Рубин',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I13','סמיון רובין','Семён Рубин',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I14','אלינה ספובל','Алина Споваль',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I15','אביב שרז','Авив Шерез',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I16','ירדן שרז','Ярден Шерез',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I17','אנטונינה דצנקו','Антонина Даценко',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I18','טטיאנה דצנקו','Татьяна Даценко',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I19','פאשה בודניקוב','Паша Будников',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I20','אלינה בודניקוב','Алина Будников',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I21','איגור בודניקוב','Игорь Будников',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I22','חוי טטרו','Хави Тетро',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I23','לני ספובל','Ленни Споваль',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I24','מיכאלה ספובל','Михаэла Споваль',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I25','טל כהן','Таль Коэн',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I26','מאי כהן','Май Коэн',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I27','אמי כהן','Эми Коэн',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I28','אירנה בלנקי','Ирена Бланки',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I29','אנסטסיה רושצ''וק','Анастасия Рощук',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I30','רפאל ספובל','Рафаэль Споваль',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I31','גנה ספובל','Гена Споваль',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I32','מארק צ''רבוננקו','Марк Червоненко',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I33','בוריס וינוגרדסקי','Борис Виноградский',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I34','מיכאל וינוגרדסקי','Михаил Виноградский',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I35','ז''ניה וינוגרדסקי','Женя Виноградский',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I36','אנה וינוגרדסקי','Анна Виноградская',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I37','דיאנה וינוגרדסקי','Диана Виноградская',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I38','לאוניד וינוגרדסקי','Леонид Виноградский',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I39','גיורא סיגין','Гиора Сигин',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I40','ליאם סיגין','Лиам Сигин',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I41','סשה רובין','Саша Рубин',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I42','רוזה רובין','Роза Рубин',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I43','סניה רובין','Сеня Рубин',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I44','טניה רובין','Таня Рубин',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I45','ריטה רובין','Рита Рубин',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I46','דניאל רובין','Даниэль Рубин',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I47','זויה רובין','Зоя Рубин',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I48','יולי שרז','Юли Шерез',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I49','רובין','Рубин',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I50','רובין','Рубин',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I51','מניה רובין','Маня Рубин',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I52','אברום רובין','Аврум Рубин',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I53','צילה רובין','Циля Рубин',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I54','דוד רובין','Давид Рубин',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I55','פולינה רובין','Полина Рубин',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I56','אנה רובין','Анна Рубин',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I57','סבטה רובין','Света Рубин',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I58','ולנטין חלוטין','Валентин Халутин',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I59','אוקסנה חלוטין','Оксана Халутин',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I60','אדי דוידוב','Эдди Давидов',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I61','נועה דוידוב','Ноа Давидов',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I62','יובל דוידוב','Юваль Давидов',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I63','דניאל דוידוב','Даниэль Давидов',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I64','דינה דוידוב','Дина Давидов',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I65','נגב דוידוב','Негев Давидов',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I66','סבטה רובין','Света Рубин',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I67','זכר','Захар',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I68','ארטיום וינוגרדסקי','Артём Виноградский',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I69','וינוגרדסקי','Виноградский',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I70','פאבל אפנאסייב','Павел Афанасьев',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I71','סטס רובין','Стас Рубин',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I72','בלומה רובין','Блума Рубин',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I73','גניה רובין','Геня Рубин',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I74','יורה סטרלביצקי','Юра Стрельбицкий',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I75','יוליה סטרלביצקי','Юлия Стрельбицкая',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I76','אלה סטרלביצקי','Алла Стрельбицкая',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I77','סטרלביצקי','Стрельбицкий',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I78','סטרלביצקי','Стрельбицкий',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I79','וינוגרדסקי','Виноградский',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I80','וינוגרדסקי','Виноградский',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I81','פייבל (ניקולאי) פחמנוב','Фейвель (Николай) Пахманов',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I82','לודמילה (שם משפחה לא ידוע)','Людмила (фамилия неизвестна)',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I83','שמול פחמנוב','Шмуль Пахманов',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I84','חיה פחמנוב','Хая Пахманов',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I85','ראיה פחמנוב','Рая Пахманов',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I86','סמיון פחמנוב','Семён Пахманов',true) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I87','שם לא ידוע','Имя неизвестно',false) on conflict (id) do nothing;
insert into public.family_people(id,name_he,name_ru,deceased) values ('I88','רחל','Рахель',true) on conflict (id) do nothing;
insert into public.family_units(id) values ('F1') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F1','I1','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F1','I22','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F1','I23','child',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F1','I24','child',1) on conflict do nothing;
insert into public.family_units(id) values ('F2') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F2','I2','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F2','I3','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F2','I1','child',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F2','I14','child',1) on conflict do nothing;
insert into public.family_units(id) values ('F4') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F4','I2','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F4','I17','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F4','I18','child',0) on conflict do nothing;
insert into public.family_units(id) values ('F3') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F3','I2','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F3','I28','parent',1) on conflict do nothing;
insert into public.family_units(id) values ('F5') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F5','I4','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F5','I5','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F5','I2','child',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F5','I30','child',1) on conflict do nothing;
insert into public.family_units(id) values ('F6') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F6','I15','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F6','I3','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F6','I16','child',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F6','I48','child',1) on conflict do nothing;
insert into public.family_units(id) values ('F7') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F7','I81','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F7','I82','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F7','I3','child',0) on conflict do nothing;
insert into public.family_units(id) values ('F8') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F8','I9','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F8','I10','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F8','I4','child',0) on conflict do nothing;
insert into public.family_units(id) values ('F9') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F9','I6','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F9','I7','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F9','I5','child',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F9','I8','child',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F9','I11','child',2) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F9','I12','child',3) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F9','I13','child',4) on conflict do nothing;
insert into public.family_units(id) values ('F10') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F10','I49','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F10','I50','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F10','I6','child',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F10','I51','child',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F10','I52','child',2) on conflict do nothing;
insert into public.family_units(id) values ('F11') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F11','I33','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F11','I8','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F11','I34','child',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F11','I35','child',1) on conflict do nothing;
insert into public.family_units(id) values ('F12') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F12','I70','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F12','I11','parent',1) on conflict do nothing;
insert into public.family_units(id) values ('F13') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F13','I12','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F13','I42','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F13','I43','child',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F13','I66','child',1) on conflict do nothing;
insert into public.family_units(id) values ('F14') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F14','I25','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F14','I14','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F14','I26','child',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F14','I27','child',1) on conflict do nothing;
insert into public.family_units(id) values ('F15') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F15','I19','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F15','I18','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F15','I20','child',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F15','I21','child',1) on conflict do nothing;
insert into public.family_units(id) values ('F16') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F16','I28','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F16','I29','child',0) on conflict do nothing;
insert into public.family_units(id) values ('F17') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F17','I30','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F17','I31','child',0) on conflict do nothing;
insert into public.family_units(id) values ('F18') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F18','I31','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F18','I32','child',0) on conflict do nothing;
insert into public.family_units(id) values ('F21') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F21','I11','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F21','I41','child',0) on conflict do nothing;
insert into public.family_units(id) values ('F23') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F23','I13','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F23','I47','child',0) on conflict do nothing;
insert into public.family_units(id) values ('F26') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F26','I56','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F26','I57','child',0) on conflict do nothing;
insert into public.family_units(id) values ('F30') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F30','I35','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F30','I68','child',0) on conflict do nothing;
insert into public.family_units(id) values ('F31') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F31','I68','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F31','I69','child',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F31','I79','child',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F31','I80','child',2) on conflict do nothing;
insert into public.family_units(id) values ('F32') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F32','I47','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F32','I71','child',0) on conflict do nothing;
insert into public.family_units(id) values ('F33') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F33','I51','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F33','I72','child',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F33','I73','child',1) on conflict do nothing;
insert into public.family_units(id) values ('F34') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F34','I72','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F34','I74','child',0) on conflict do nothing;
insert into public.family_units(id) values ('F35') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F35','I74','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F35','I75','child',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F35','I76','child',1) on conflict do nothing;
insert into public.family_units(id) values ('F36') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F36','I76','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F36','I77','child',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F36','I78','child',1) on conflict do nothing;
insert into public.family_units(id) values ('F19') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F19','I34','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F19','I36','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F19','I37','child',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F19','I38','child',1) on conflict do nothing;
insert into public.family_units(id) values ('F20') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F20','I39','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F20','I37','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F20','I40','child',0) on conflict do nothing;
insert into public.family_units(id) values ('F22') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F22','I43','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F22','I44','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F22','I45','child',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F22','I46','child',1) on conflict do nothing;
insert into public.family_units(id) values ('F24') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F24','I52','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F24','I53','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F24','I54','child',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F24','I55','child',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F24','I56','child',2) on conflict do nothing;
insert into public.family_units(id) values ('F25') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F25','I58','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F25','I57','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F25','I59','child',0) on conflict do nothing;
insert into public.family_units(id) values ('F27') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F27','I60','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F27','I59','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F27','I61','child',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F27','I62','child',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F27','I63','child',2) on conflict do nothing;
insert into public.family_units(id) values ('F28') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F28','I63','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F28','I64','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F28','I65','child',0) on conflict do nothing;
insert into public.family_units(id) values ('F29') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F29','I67','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F29','I66','parent',1) on conflict do nothing;
insert into public.family_units(id) values ('F37') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F37','I83','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F37','I84','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F37','I81','child',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F37','I85','child',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F37','I86','child',2) on conflict do nothing;
insert into public.family_units(id) values ('F38') on conflict (id) do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F38','I87','parent',0) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F38','I88','parent',1) on conflict do nothing;
insert into public.family_members(family_id,person_id,role,sort_order) values ('F38','I84','child',0) on conflict do nothing;
